version: "3"
services:
  elixirapp:
    build: .
    image: elixirapp:latest
    command: mix phx.server
    environment:
      MIX_ENV: prod
      PORT: 4000
      REDIS_URL: redis://redis:6379
    ports:
      - "4005:4000"  
    links:
      - redis
    depends_on:
      - redis
    networks:
      - applocal
  redis:
    image: redis:latest
    networks:
      - applocal
networks:
  applocal:
    driver: bridge